dmwm/CRABClient

- src/python/CRABClient/client_utilities.py
Changed getBasicConfig to basicConfig
Added section Debug.
> Pre-populate sections in config? Fixes #4519

- src/python/CRABClient/JobType/CMSSWConfig.py
> Get only the filename and not the whole path from the edm filenames. Fixes #4348

- src/python/CRABClient/client_utilities.py
Added get FileFromURL. User now are able to fetch any type of code from URL.
> Allow fetching of PSet by URL. fixes #4357

- src/python/CRABClient/ClientMapping.py
Needed for https://github.com/dmwm/CRABServer/issues/4565
> Possibility specify collector.

- src/python/CRABClient/Commands/status.py
...lable; state more clearly in the log message when the publication flag has been set to false. Fixes #4344.
> Show output dataset name even if the publication information is not available

- bin/crab
- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/UserTarball.py
Also, use cammelCase in ClientMapping.
> Include all config params in client mapping. Add reverted mapping and use it where possible.

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/JobType/Analysis.py
Fixes https://github.com/dmwm/CRABServer/issues/4244
> Change Data.userInputFile to Data.userInputFiles, and accept a python list instead of a text file.

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/PrivateMC.py
Don't merge yet. First merge https://github.com/dmwm/CRABClient/pull/4402, then I will rebase my pull request.
> Accept only one of Data.inputDataset and Data.userInputFiles. When running over user input files accept only FileBased splitting.

- src/python/CRABClient/Commands/status.py
Fixes: https://github.com/dmwm/CRABServer/issues/4676
> Show condor cluster.id in crab status --long

- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/submit.py
Don't harcode list-parameters in resubmit command.
> Some changes in resubmit command.

- src/python/CRABClient/Commands/SubCommand.py
As per @belforte request in https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2314/1/1.html
> Change message when --task is used.

- src/python/CRABClient/ClientMapping.py
Fixed https://github.com/dmwm/CRABClient/issues/4438
Fixed https://github.com/dmwm/CRABClient/issues/4219
> Changed outLFN and allowNonProductionCMSSW config parameter name.

- src/python/CRABClient/Commands/status.py
1) Introduce --verboseErrors option for the error summary.
If this option is not specified, the error summary is like this (notice I also sorted from most frequent to less frequent exit codes):
Error Summary: (use --verboseErrors for details about the errors)
123 jobs failed with exit code 134
18 jobs failed with exit code 8020
17 jobs failed with exit code -1
8 jobs failed with exit code 8001
6 jobs failed with exit code 80000
6 jobs failed with exit code 8002
6 jobs failed with exit code 65
3 jobs failed with exit code 10040
1 jobs failed with exit code 10034
If --verboseErrors is given, show the (3 most frequent) error messages for each exit code.
2) Fix the sorting by exit code in status --sort=exitcode.
3) When --sort=exitcode is specified, apply it also to the error summary (i.e. …
> Improvements in crab status error summary and --sort=exitcode.

- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/getcommand.py
- src/python/CRABClient/Commands/uploadlog.py
This is for issue #4454 but not sure you want to close it or not.
> Check if valid CRAB project directory.

- etc/crab-bash-completion.sh
- scripts/generate_completion.py
Fix internal renaming changes and class changes in CRAB.  Provides a
new command line completion script, too.
Fixes: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/616.html
> Update the command completion script.

- src/python/CRABClient/Commands/resubmit.py
I will make the corresponding pull request for the server once https://github.com/dmwm/CRABServer/pull/4773 is merged. So don't merge this pull if you don't plan to merge https://github.com/dmwm/CRABServer/pull/4773
> Add --force option in resubmit command.

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Requires https://github.com/dmwm/CRABServer/pull/4844
> Add Data.publishWithGroupName parameter to CRAB config.

- bin/crab
- bin/crab3bootstrap
- src/python/CRABAPI/RawCommand.py
- src/python/CRABClient/ClientUtilities.py
Don't merge. I will rebase once https://github.com/dmwm/CRABClient/pull/4506 is merged.
> Flush memomy handler to crab.log file and remove handlers after executing commands via crabCommand.

- src/python/CRABClient/Commands/status.py
The output of crab status (for the case of 0 failed jobs) and 15 files with failed publications would look something like this:
```
CRAB project directory:		/afs/cern.ch/work/a/atanasi/crab3/CMSSW_7_3_5_patch2/src/crab_test_report_on_doublelumis_input_dataset_2
Task name:			150731_154344:atanasi_crab_test_report_on_doublelumis_input_dataset_2
Task status:			SUBMITTED
Warning:			The CRAB3 server backend detected lumis split across files in the input dataset. Will apply the necessary corrections in the splitting algorithms. You can ignore this message..
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150731_154344%3Aatanasi_crab_test_report_on_doublelumis_input_dataset_2
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/# …
```
> Print publication failure reasons in crab status. Fixes #4530

- bin/crab
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/UserTarball.py
Requires https://github.com/dmwm/CRABServer/pull/4931 (otherwise will just show same message as before).
Example of produced output:
```
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration pset_tutorial_analysis.py
Finished importing CMSSW configuration pset_tutorial_analysis.py
Error: Input sanbox size is ~157MB. This is bigger than the maximum allowed size of 100MB.
Input sanbox content sorted by size[Bytes]:
30335025    files_for_sandbox/MVI_0132.MOV
3369774	files_for_sandbox/IMG_0149.JPG
3203026	files_for_sandbox/IMG_0129.JPG
3187637	files_for_sandbox/IMG_0130.JPG
3105704	files_for_sandbox/IMG_0116.JPG
3103565	files_for_sandbox/IMG_0138.JPG
3019446	files_for_sandbox/IMG_0125.JPG
2840900	files_for_sandbox/IMG_0096.JPG
2826687	files_for_sandbox/IMG_0111.JPG …
```
> Improve error message for input sandbox size limit exceeded. Fixes #4527

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/JobType/Analysis.py
Needed for dmwm/CRABServer#4934.
> Allow to specify a secondary dataset.

- src/python/CRABClient/Commands/checkwrite.py
- src/python/CRABClient/Commands/getcommand.py
- src/python/CRABClient/Commands/remote_copy.py
Commands to test: (Better all sites, specially US and other storage elements)
```
crab checkwrite --site=T2_CH_CERN
crab checkwrite --site=T2_CH_CERN --command=LCG
crab checkwrite --site=T2_CH_CERN --command=GFAL
crab checkwrite --site=T2_CH_CERN --command=LCG --checksum=True
crab checkwrite --site=T2_CH_CERN --command=GFAL --checksum=True
crab checkwrite --site=T2_CH_CERN --command=LCG --checksum=False
crab checkwrite --site=T2_CH_CERN --command=GFAL --checksum=False
crab checkwrite --site=T2_CH_CERN --command=LCG --checksum=fakeText
crab checkwrite --site=T2_CH_CERN --command=GFAL --checksum=fakeText
```
It will always use checksum, but user can disable it by specifying False option. This is needed until we move to check checksum from database and also all sites will support checksum. …
> Allow to choose command and checksum(True/False)

- bin/crab3bootstrap
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/UserUtilities.py
This PR is for https://github.com/dmwm/CRABServer/issues/4982 Ohhh, I didn't see Stefano's comment that he volunteered to do this.. sorry...
> Add user function getLumiListInValidFiles

- bin/crab
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/remote_copy.py
The interesting commit is the last one
> get(log|out) did not print error messages in the logfile

- bin/crab2cfgTOcrab3py
- doc/FullConfiguration.py
- doc/config/FullConfiguration.py
- doc/crabclient/userdoc/running.rst
- src/python/CRABAPI/test_Task.py
- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/PrivateMC.py
- test/data/mapper.py
> Change some CRAB config parameter names.

- src/python/CRABClient/Commands/resubmit.py
PR in the server: https://github.com/dmwm/CRABServer/pull/5081
> Add --publication option to resubmit command. Fixes #4077.

- bin/crab
- src/python/CRABClient/JobType/PrivateMC.py
Moving this check to the server.
> Remove check of no input dataset in PrivateMC.

- src/python/CRABClient/ClientUtilities.py
Fixes https://github.com/dmwm/CRABServer/issues/5111
> Show (re)submission failure message in crab (re)submit --wait.

- bin/crab3bootstrap
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/JobType/PrivateMC.py
> Fix error message for 'outputPrimaryDataset'

- src/python/CRABClient/Commands/status.py
make it very clear how to use --verbodeErrors, since someone did not get it from current text
> improve message to user

- src/python/CRABClient/CredentialInteractions.py
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1421.html
> Revert Use clean env for proxy delegation #4594

- src/python/CRABClient/Commands/report.py
changing
dbsInLimilistNewClientOldTask
to
dbsInLumilistNewClientOldTask
> fixing a typo in report.py line 100

- src/python/CRABClient/Commands/submit.py
Use a regular expression to parse the Condor settings and shlex to split
setting values.
Fixes dmwm/CRABServer#5125
> Dry-run: Parse Condor DAG and JOB_AD files better.

- src/python/CRABClient/JobType/PrivateMC.py
made text a bit more clear to reader and to users. @matz-e do you like it ?
> improve message for #4612

- src/python/CRABClient/JobType/LumiMask.py
Issue opened on CRABServer: https://github.com/dmwm/CRABServer/issues/5077
> Handle exceptions when accessing lumiMask file

- src/python/CRABClient/CredentialInteractions.py
Since #4532 seems to be a very rare error, this is the simplest way of taking care of it that I can see. I'd gladly hear some suggestions though if there's a better solution.
> Catch exception when getting the time left on the proxy. Fixes #4532

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Server PR: https://github.com/dmwm/CRABServer/pull/5306
Server issue: https://github.com/dmwm/CRABServer/issues/4664
> Put ignoreGlobalBlacklist flag in the DB.

- src/python/CRABClient/Commands/status2.py
Has to be merged together with https://github.com/dmwm/CRABServer/pull/5326 in order for status2 to work.
> Minor fix for status2 cache file format change

- src/python/CRABClient/Commands/purge.py
@mmascher please review rational for this as described in the comments in #4667 and https://github.com/dmwm/CRABServer/issues/5360
> allow to purge tasks in SUBMITFAILED fix #4667

- src/python/CRABClient/Commands/status2.py
Issue on CRABServer https://github.com/dmwm/CRABServer/issues/5294
This will print only the selected jobids in crab status --long as well as --sort if the parameter --jobids is used. status --long / status --sort will not be printed if non-existent jobids are given by the user.
> Add --jobids parameter to crab status2 --long and --sort

- etc/crab-bash-completion.sh
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2781.html
I just ran `scripts/generate_completion.py`…
> Update bash completion script

- src/python/CRABClient/Commands/status.py
@mmascher This will handle the changes we've made over the last days.
> Update status command to take multiple probe jobs into account.

- src/python/CRABClient/Commands/getlog.py
- src/python/CRABClient/Commands/getlogold.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/status.py
- src/python/CRABClient/UserUtilities.py
According to the logic outlined here: https://github.com/dmwm/CRABClient/issues/4702#issuecomment-303737455. I'll review next week with @mmascher when he's around though now I'm pretty sure this will do what we said it would in that thread.
> Combine task statuses into a single one

- src/python/CRABClient/Commands/kill.py
I think this is all that needs to be done on the client for https://github.com/dmwm/CRABServer/issues/5512, there's also some code cleanup required on the server.
> Disable kill --jobids

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/report.py
Issue reported here https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3064.html
> Minor unicode/tarfile fixes for old CMSSW versions

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/getcommand.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/status.py
Skip probe jobs where appropriate.
> Fixes for automatic splitting

- src/python/CRABClient/Commands/status.py
For automatic splitting only (probe jobs present).  Since processing jobs
cannot be resubmitted with automatic splitting, they should not be
accounted for in the publication total.
> Remove failed processing jobs from publication total.

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/status.py
Along with #4748 resolves #4732, #4733 and #4739.
> Status issues

- src/python/CRABClient/Commands/status.py
The client queries the RESTInterface which executes
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L933
with this Oracle FileTransfersDB query:
https://github.com/dmwm/CRABServer/blob/9b3837b94aeb26fde76790c111e13f4f2034a90d/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py#L246
> Resolve #4740

- src/python/CRABClient/Commands/status.py
Some users asked for clarification because they did not read the documentation.
> Pointer to Automatic slitting FAQ

- src/python/CRABClient/Commands/kill.py
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3943.html
> Remove deprecated jobids option from kill command help

- src/python/CRABClient/Commands/status.py
> scheduler and tw name in one line, fix #4777

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/resubmit.py
Need to make `server` an instance attribute (`self.server`) in order to use it in two functions.
`self.proxyfilename` is set by: 
https://github.com/dmwm/CRABClient/compare/master...lecriste:OriginalConfigBug?expand=1#diff-d4868c145f287841a40217516e1cb809L276
> Resolve #4774

- src/python/CRABClient/Commands/status.py
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4512.html
> Clarify warning message

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/resubmit.py
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4525/2.html
> Restore original behaviour of 'crab submit'

- src/python/CRABClient/Commands/status.py
@belforte, shall we print [this](https://github.com/dmwm/CRABClient/compare/master...lecriste:improve-crab_status?expand=1#diff-ff67af59351a4436cecb26ca2051f7b8R357) in a different color till the colon?
> Add Grafana dashboard link

- src/python/CRABClient/Commands/status.py
- src/python/CRABClient/JobType/CMSSWConfig.py
Fail submission when the dump of CMSSW configuration file cannot be done.
> Resolve part of #4809

- src/python/CRABClient/JobType/Analysis.py
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5301/1/1.html
> Do not display warning with empty files list

- src/python/CRABClient/Commands/submit.py
> Resolve #4853

- src/python/CRABClient/Commands/kill.py
- src/python/CRABClient/Commands/purge.py
Bug reported in
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5478.html
> Revert part of #4865

- bin/CreateProxy.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/CredentialInteractions.py
This reverts commit d8315271e9d2549a0afee7a3dfc0a552cc8f6fc2.
But that commit was also disabling DBS API calls replacing with dasgoclient.
I  need to add back that change
> Revert "No old style proxy login (#4922)"

- etc/crab-bash-completion.sh
- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/createmyproxy.py
> add createmyproxy command

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/CredentialInteractions.py
> always use openSSL to get CertEndDate. Revert #ff2afed  and fix #4955

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/createmyproxy.py
- src/python/CRABClient/CredentialInteractions.py
improve messages about myproxy renewal and print credential names in crab myproxy
fixes problems found in validation of v3.201109  #4958
> Better my proxy messages

- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/UserTarball.py
this should have been in last tag :-(  but was  missed by distraction
> Adapt to crabserver v3.210410

- src/python/CRABClient/ClientMapping.py
> submit by default to preprod instead of prod (fix #5075)

- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/BasicJobType.py
- src/python/CRABClient/JobType/CopyCat.py
- src/python/CRABClient/JobType/LumiMask.py
- src/python/CRABClient/UserUtilities.py
tested using CMSSW_7_6_7, CMSSW_10_2_6 CMSSW_12_0_1 releases
> use lumilist from CMSSW

- src/python/CRABClient/CrabRestInterface.py
tested on CMSSW_7_6_7, CMSSW_10_2_6, CMSSW_12_0_1
> pass file instead of data to curl request (fix #5105)

- src/python/CRABClient/WMCoreConfigWrapper.py
credits for idea/implementation goes to @mapellidario !
this should go together with https://github.com/ddaina/cmsdist/commit/406c233e2b08948dc6998582d8d6708200db17ab
> add Wrapper for WMCore configuration

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
To solve https://github.com/dmwm/CRABClient/issues/5164 and #5163
Add `Data.partialDataset` options, allow user to run task on dataset that partially on disk. See https://github.com/dmwm/CRABServer/issues/7135 for more info.
> Add Data.partialDataset option #5164

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
deprecate publishWithGroupName as per https://github.com/dmwm/CRABServer/issues/7359
> deprecate publishWithGroupName

- src/python/CRABClient/JobType/CMSSWConfig.py
> Make sure numberOfThreads is uint32 in the PSet

- src/python/CRABClient/JobType/UserTarball.py
includes a few small pylint fixes
> skip .git directories when creating sandbox. Fix #5202

- bin/crab
- bin/crab.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/BasicJobType.py
- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/JobType/CopyCat.py
- src/python/CRABClient/JobType/LumiMask.py
- src/python/CRABClient/LumiList.py
- src/python/CRABClient/UserUtilities.py
This was tested already in a separate branch. https://github.com/dmwm/CRABClient/issues/5221#issuecomment-1772759113 and following
So it is safe. In case we can simply adjust where the switch to python3 starts in `bin/crab`
> Use python3 and rucio client with cmssw 10

- etc/crab-bash-completion.sh
- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/checkfile.py
initial version. Works, but details of what is reported, how, and possibly other/different checks needs to be tuned based on experience.
E.g. I have put some `print` statements which make output prettied on console, but may be messy if this is used via python API. 
**N.B.** I have not tested `--instance` nor `--scope` options. I am not even sure `--scope` is useful
Ref: https://github.com/dmwm/CRABClient/issues/5234
> add checkfile.py fix #5234

- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/Commands/preparelocal.py
also a small change to the Hellp message for `--instance`
> preparelocal creates one json file with args for job. Fix #5276

- etc/crab-bash-completion.sh
- scripts/generate_completion.py
> Fix autocompletion

- src/python/CRABClient/Commands/preparelocal.py
- src/python/CRABClient/Commands/submit.py
> make --dryrun work again with TW v3.2411xx

- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/Commands/recover.py
- src/python/CRABClient/Commands/report.py
> Improve recover help 5295

- bin/crab.py
- src/python/CRABClient/JobType/CMSSWConfig.py
see https://github.com/dmwm/CRABClient/issues/5299#issuecomment-2997248991 for a preview of how stdout and log will look like after this change
> better reporting of exceptions. Fix #5299

- src/python/CRABClient/CRABOptParser.py
> make instance in config. file work again and add comment

- src/python/CRABClient/Commands/report.py
also simplify things a bit and changes for pylint
> Pull input files and lumis list from S3. Fix #5368
