dmwm/CRABClient

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/BasicJobType.py
- src/python/CRABClient/JobType/PrivateMC.py
Also:
1) Require Data.primaryDataset in PrivateMC.
2) Don't accept Data.primaryDataset in Analisys job type.
3) Move the spellchecking of the configuration parameters from submit::\__call\__ to SubCommand::validateConfig (which if called in SubCommand::\__init\__ when loading the config)
4) Some small changes in messages to user when validating the config and in crab report.
> Add protection to avoid PrivateMC with inputDataset.

- src/python/CRABClient/Commands/remote_copy.py
If transfer failing due to :   
1. Timeout
2. Wrong size
3. Failure deletion of file if size is not correct
All these exceptions are catched and reported to user, but also if any exception happens, function returns and subprocess is removed(not getting any new transfer request). When all subprocesses (10 or N which user specified) end up any of this error, we are getting 'Broken Pipe' error. Don`t return until queue still have work to do.
> crab getoutput fix Broken pipe. Fixes #4221

- src/python/CRABClient/Commands/status.py
To know how many files there are to publish, I multiply the number of jobs in the task by the number of output datasets. This assumes that each EDM file produced in a job goes into a different output dataset (the post-job is putting each EDM file of a job into a different output dataset, where the name of the PoolOutputModule is added to the output dataset name).
Test: I produced two EDM files in my pset, running only 1 job. This is the crab status output:
$ crab status -d crab_check_multi_EDM_1
WARNING: Incompatible CRABClient version "development" 
Server is saying that compatible versions are: ['3.3.12', '3.3.12.patch1', '3.3.12.rc7']
Task name:			150119_084637_crab3test-1:atanasi_crab_check_multi_EDM_1
Task status:			COMPLETED
Glidemon monitoring URL: …
> In publication status, fix count of number of files to publish. Fixes #4374.

- src/python/CRABClient/Commands/status.py
Old CRABClient will not work with new CRABServer and we have to make sure that it is backward compatible.
> New CRABServer returns publication info with disabled

- src/python/CRABClient/UserUtilities.py
This way the user can do
import CRABClient
config = CRABClient.Config()
as suggested by @belforte in https://github.com/dmwm/CRABServer/issues/4519. 
@belforte Now that we have introduced the module CRABClient.UserUtilities which contains all functions that we expose to users (including Config() -which is still called basicConfig()-), do you still prefer the above for the config, or you prefer to keep Config() inside CRABClient.UserUtilities?
Other question I have also is: If the user wants to use the functions from CRABClient.UserUtilities, how should we tell him/her to use these functions? Two options below:
1) Only import CRABClient and he/she gets everything, but then calling a function from CRABClient.UserUtilities requires to always put CRABClient.UserUtilities:
import CRABClient …
> Rename basicConfig to config.

- src/python/CRABClient/client_utilities.py
Test:
I included in my crabConfig_test.py file:
from CRABClient.client_utilities import getBasicConfig
config = getBasicConfig()
$ crab submit -c crabConfig_test.py
Will use configuration file crabConfig_test.py.
Warning: The method getBasicConfig is now available in the CRABClient.UserUtilities module (with new name 'config'). From 1 April 2015, loading getBasicConfig from CRABClient.client_utilities will not be possible anymore (CRABClient.client_utilities will be removed). Please change your code accordingly before 1 April 2015.
> Old 'config' function was named 'getBasicConfig', not 'basicConfig'.

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/submit.py
When I moved the spell checking to the SubCommand validateConfig(), this was taking precedence over the check of renamed parameters, which was done later in the validateConfig of the submit command.
I think it makes sense to move the check of renamed parameters to the SubCommand validateConfig, as it is a general config validation necessary not only for the submit command. And we should do it before the spell checking. I also moved the check of the sections definition to the SubCommand validateConfig.
> Move check of renamed parameters from submit to SubCommand.

- src/python/CRABClient/Commands/remote_copy.py
Adding more print information which command will be used and
If no gfal or lcg-cp exists reporting to contact site admin Fixes #4385
Correctly report file successfully retrieved. Fixes #4384
>  Improvementes to remote_copy

- scripts/generate_completion.py
Options for subcommands will only be completed when a leading `-` has
already been typed.  No checks for optional arguments are done.
Uses introspection to determine available options and subcommands.
Fixes #4391.
> Add a simple bash completion generation script.

- src/python/CRABClient/Commands/SubCommand.py
Fixes: https://github.com/dmwm/CRABServer/issues/4213
Ranges and wildcards are now possible.
Accepted wildcard example: "3.3.3\*". This will be intepret as 3.3.3, 3.3.3.pre2, 3.3.3.patch1 etc.
Accepted range example: "3.3.1-3.3.3". This will be intepret as 3.3.1\*, 3.3.2\*, 3.3.3
"3.3.1-3.3.3\*".This will be intepret as 3.3.1\*, 3.3.2\*, 3.3.3\*
Msg for the user will still show the one from gist and not from the long list.
> Accept ranges and wildcards for compatible-version in external configuration (gist)

- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/JobType/PrivateMC.py
Addresses part of dmwm/CRABServer#4659.  While a framework fix will solve said issue, at
least warn users that the task may not supported by CMSSW as submitted.
This will make the `generator` parameter in the `JobType` section optional / for advanced use only, as `LHESource`s will be auto-detected.
> Add LHESource detection and print warning for multiple LHE files.

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/proceed.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/submit.py
Example output:
```
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Waiting for task to be processed
Checking task status
Task status: NEW
Please wait...
Task status: UPLOADED
Executing local test run (needed for timing estimates), please wait...
Using LumiBased splitting
Task consists of 301 jobs to process 3009 lumis
The estimated memory requirement is 1306 MB
The longest job will process 10 lumis, with an estimated processing time of 142 minutes
The average job will process 9 lumis, with an estimated processing time of 142 minutes
The shortest job will process 9 lumis, with an estimated processing time of 128 minutes
Dry run requested: task paused
To continue processing, use 'crab proceed'
```
> Add a 'dryrun' option for crab submit.

- src/python/CRABClient/Commands/getlog.py
- src/python/CRABClient/Commands/remote_copy.py
- src/python/CRABClient/UserUtilities.py
Fixes https://github.com/dmwm/CRABServer/issues/4637
User can do 'crab getlog --short -dir <task name> --jobids=<job ids>' to get the short version of the log file.
> crab getlog --short

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/status.py
As per @belforte suggestion in https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2314/1/1.html
> Add CRAB project directory to crab status output. In the .crab3 file, change the key name from 'taskname' to 'crab_project_directory'.

- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/Commands/SubCommand.py
A guess nobody at this point will try to use the --task option. Python option parser will anyway give the error:
Usage: crab status [options] [args]
crab: error: no such option: --task
> Remove code about old --task option.

- src/python/CRABClient/JobType/Analysis.py
@belforte Do you want to suggest a better message?
> Give warning message in case no output file was detected in the CMSSW pset nor was any specified in the CRAB configuration.

- bin/crab
- bin/crab.sh
- bin/crab3bootstrap
- doc/FullConfiguration.py
- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/ClientExceptions.py
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/JobType/ScramEnvironment.py
Provides two new scripts:
crab.sh: wrapper script that does scram unset env before running crab
commands. Also, if the command is a submit run the bootstrap script
crab3bootstrap: executes all the operations that needs the CMSSW
environment saving the output to a tmp dir. Returns the tmp directory or
the error message in case of errors.
Backward compatibility is guaranteed since the bootstrapDone() function
is called to check if the clients needs to perform the CMSSW related
operations or the bootstrap script was run.
also refactored many parts of the client. We are providin now:
flushMemoryLogger function that group the code used to save the output messages that
are stored in memory
validateSubmitOptions to group the code that in the crab submit
command validate the command line options …
> Separate COMP and CMSSW envs. Fixes #4300

- bin/crab
- bin/crab3bootstrap
- src/python/CRABAPI/RawCommand.py
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/UserUtilities.py
A user can do:
from CRABAPI.RawCommand import crabCommand
from CRABClient.UserUtilities import getConsoleLogLevel, setConsoleLogLevel, noLogInfo
origLogLevel = getConsoleLogLevel()
crabCommand(...) # will not be quiet
setConsoleLogLevel(noLogInfo)
crabCommand(...) # will be quiet
crabCommand(...) # will be quiet
setConsoleLogLevel(origLogLevel)
crabCommand(...) # will not be quiet
Are you ok with the name of the constant "noLogInfo"? I was thinking otherwise of something like "LOGLEVEL_MUTE"
> Add setConsoleLogLevel function to control console handler log level. Fixes #4418

- src/python/CRABClient/JobType/PrivateMC.py
To track releases, see the following commits:
https://github.com/cms-sw/cmssw/commit/b52beebeb3292e674259df8b4f05c1703f86f374
https://github.com/cms-sw/cmssw/commit/2183765fd615b6402cb80c36f50ef0baa3fb6d92
This does **not** catch pre-releases, which should be run at your own risk,
anyways.
I will add support for releases with the fix added at least as long as this PR is open.  Will eventually fix dmwm/CRABServer#4659
> Remove LHE file warning for appropriate releases.

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/status.py
Requires https://github.com/dmwm/CRABServer/pull/4976
> Improve crab status output for failed tasks. Consider new task statuses SUBMITFAILED and RESUBMITFAILED in checkStatusLoop.

- src/python/CRABClient/JobType/BasicJobType.py
Hi,
I found this issue when investigating why `crab report` takes ages when ran over a big task (> 100 jobs). In my case, running `crab report` on `DY M-50` took approximately 30 minutes ... Looking at the crab log, I've seen that something fishy occurs between the server response and the first log output:
```
DEBUG 2015-12-02 15:55:34,663:   Result: <...>
INFO 2015-12-02 16:28:23,413:    683 files have been processed
```
I've been able to pinpoint the issue to the function `getDoubleLumis`, which find the duplicated lumi sections. I've changed a bit the code of the function, which lead to a huge gain in runtime. In my test-case, I have only one run (it's MC), and 299900 lumi-sections. Runtimes are:
- Original code: > 20 mins (I stop the execution)
- New code: ~ 500ms
It'd be great if …
> Optimize getDoubleLumis function speed

- src/python/CRABAPI/RawCommand.py
Documentation of the crabCommand API already updated in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI
> Support options without value in kwargs of crabCommand. Fixes #4577

- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/BasicJobType.py
On top of what is discussed in #4522, I also: 
* Removed --usedbs option, because in the report the output/input datasets lumis are always returned (the input datasets lumis from a file saved at data discovery time).
* Added --failed option (feel free to suggest a better name): accepts a comma-separated list of jobs states, e.g. `--failed=failed,killed`, in which case the report will return as the not-processed lumis the lumis that all jobs in those states should have processed. Otherwise the default for not-processed lumis is = lumis in run_and_lumis.tar.gz - processed lumis.
This PR has a counterpart in the server: https://github.com/dmwm/CRABServer/pull/5046. The server PR is backward compatible with current client and with old tasks.
> Fixes for crab report command. Fixes #4522

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/checkwrite.py
This is needed if we want to use the lightweight specfile
> Make sure pycurl is always used (WMCore default is httplib)

- etc/init-light.csh
- etc/init-light.sh
Adding an init-light.csh script to make the light CRABClient compatible with cshell.
> Modified bash script to work with cshell, new init-light.csh file

- src/python/CRABClient/Commands/report.py
The lines being removed were needed for backward compatibility with tasks submitted before CRAB 3.3.1603 (the release with the new crab report code). After 1 month, I guess you don't care anymore about this backward compatibility.
> Remove code for backward compatibility with old tasks.

- bin/crab3bootstrap
- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/JobType/PrivateMC.py
We receive a lot of emails with misconfigurations when generating MC.  This
will test the input source of the parameter set and try to point the user
to potential fixes before the task hits the crab server and fails.
Fixes #4610.
> Explicitly test parameter set input configuration for PrivateMC.

- etc/init-light.sh
Fixes an issue discovered during validation [*] where external arguments (from user scripts, for example) were being automatically propagated to the crab_light.SH script and confusing it. 
Now, instead of exiting, if the first argument is not "-csh", the script defaults to bash for sourcing the environment. As it was before, if the crab_light.CSH script is used, a "-csh" argument is passed to the .SH script and thus the CSH envronment is sourced.
[*] https://github.com/dmwm/CRABServer/issues/5209#issuecomment-216471062
> Deal with outside CL arguments passed to crab_light.sh

- src/python/CRABClient/JobType/Analysis.py
- src/python/CRABClient/JobType/UserTarball.py
Issue discussed on crabserver: https://github.com/dmwm/CRABServer/issues/5153
Pull request on crabserver: https://github.com/dmwm/CRABServer/pull/5236
> Separate Ops monitoring files into another tarball. Fixes #5153 in CRABServer

- src/python/CRABClient/Commands/status.py
Because Marco modified the server to provide the username for the client, querying external services is for that reason can sometimes be avoided. I've removed most of the code from Stefano's pull request about improving the dashboard url provided by the status and now get the username from the server.
> Generate Dashboard URL without querying SiteDB. Fix #4622

- src/python/CRABClient/JobType/Analysis.py
A minor bugfix for when a tarball upload fails and a variable is not initialized.
> Check if debug tarball upload result variable exists. #4630

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/JobType/UserTarball.py
Requested by a few users: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1972.html. It's possible to work around not having this option by using symlinks, but the code is simple and shouldn't cause any troubles.
> Add option to include the external directory in the user tarball

- src/python/CRABClient/JobType/Analysis.py
Discovered a small problem during validation with the CMSSW_5_3_22 environment [*] having an older pycurl version and not working well with unicode, this should fix it.
[*]
```ERROR 2016-11-07 13:49:19,470:   Impossible to calculate the checksum of the sandbox tarball.
Error message: invalid arguments to setopt.
More details can be found in /afs/cern.ch/user/e/erupeika/crab_projects/crab_1611_test_mon41/crab.log
Traceback (most recent call last):
File "/afs/cern.ch/user/e/erupeika/private/github/repos/CRABClient/src/python/CRABClient/JobType/Analysis.py", line 152, in run
uploadResult = tb.upload(filecacheurl = filecacheurl)
File "/afs/cern.ch/user/e/erupeika/private/github/repos/CRABClient/src/python/CRABClient/JobType/UserTarball.py", line 144, in upload
result = ufc.upload(archiveName, …
```
> Old CMSSW compatibility fix - removing unicode

- src/python/CRABClient/JobType/Analysis.py
Have to make another[*] commit for the same problem since I ended up ignoring the missing debug tarballs previously. 
[*]
https://github.com/dmwm/CRABClient/commit/230385d34a144bfe6e37a18635d385184cf59d43
> Fix another occurence of unicode incompatible with some pycurl versions

- src/python/CRABClient/Commands/report2.py
This dict can be empty and should give the user "Cannot get all the needed information for the report." error in case it is.
> Check if returned runsAndLumis dict is empty in report2

- src/python/CRABClient/Commands/resubmit2.py
Resubmit2 throws an exception because of a missing dict element if a jobId of a job that doesn't exist is passed with the --jobids parameter.
> Check if jobId passed by user to resubmit2 exists

- src/python/CRABClient/Commands/report2.py
The resulting dictionary from the method getLumisToProcess() is assigned to the correct reportData key  already in collectReportData() here https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/report2.py#L323. Therefore, with the current behavior, lumisToProcess gets nested twice under the same key 'lumisToProcess'  (reportData['lumisToProcess']['lumisToProcess']) which is incorrect.
> Fix lumisToProcess.json in report2

- src/python/CRABClient/Commands/status2.py
Using the getFileFromURL() method the downloaded status_cache file currently gets saved to the directory wherever the command was ran from. With this path, it should be saved to the task's results directory. 
Not sure if we should keep using the getFileFromURL() since there's no real reason in saving the output to a file. I could make a separate method instead, readFileFromURL.
> Save downloaded st2 cache file in results dir

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Analysis.py
Issue on CRABServer: https://github.com/dmwm/CRABServer/issues/5321.
Since there's no real need to store this list in the database, I'm removing it. The client simply won't send this parameter to the server anymore and the server will default the value to an empty list.
This is the first step, the next one is to remove this parameter from the server and the database. The second step should be done in a different release so that we don't end up with outdated clients after the deployment sending a value to the server which is no longer expected.
> Don't send additional input files list to server

- src/python/CRABClient/Commands/status2.py
Some of the printouts for the --sort option were misaligned (like retries or cpu) because of missing newlines, kind of making the option useless. This has also been around for a very long time AFAICT. Simple to fix however, so why not.
> Fix status2 --sort formatting

- bin/crab
There's no need for this print because the optparse already writes to stdout. The print invokes the method but also prints the return value of the method, which is `None`, so it appears in the output as well.
```
(Pdb) print(self.parser.print_help()) 
Usage: crab [options] COMMAND [command-options] [args]
Options:
--version   show program's version number and exit
-h, --help  show this help message and exit
--quiet     don't print any messages to stdout
--debug     print extra messages to stdout
Valid commands are: 
checkusername
checkwrite (chk)
getlog (log)
getlog2 (log2)
getoutput (output) (out)
getoutput2 (output2) (out2)
kill
proceed
purge
remake (rmk)
report (rep)
report2 (rep2)
resubmit
resubmit2
status (st)
status2 (st2)
submit (sub)
tasks
uploadlog (uplog)
To get single command …
```
> Minor bugfix when printing CRAB help message

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Move the error message to the configuration validation for all other
splitting modes.
> Provide a default time for Automatic splitting.

- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/status.py
This dictionary should now contain all of the old status information, minus a few unused keys (                  "failedJobdefs", "totalJobdefs", "jobdefErrors") plus a few new keys required for other commands. It's not a massive change in any sense but still could break something I didn't foresee.
> Make status2 return dict (mostly) backwards compatible

- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/status.py
- src/python/CRABClient/UserUtilities.py
Not exactly well tested but should work. I had to refactor some other code, in crab report I now use getFileFromUrl instead of constructing a pycurl request because I think it makes it easier to pass the user's proxy with the request.
> Use proxied webdir for file downloads in new commands

- src/python/CRABClient/Commands/getcommand.py
There was an issue reported by the user about the new `getoutput` command not working [1] (server responds with an error, URI too long). This happened because the GET request, which the client send to the server to retrieve file metadata, was too long. In the GET request, each jobid which the user is wants is specified. This means that if there are 1000 jobs for which we can retrieve the output, the request will have 1000 separate jobids parameters, looking something like this [2].
The request size was not an obvious problem with the old commands because by default the client was not sending the full list of jobids to be processed. However, `crab getoutputold --jobids='1-1000'` will most certainly fail with the same error because in this case the client sends the jobids to the server with …
> Add limit on number of files for getoutput/getlog

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/UserUtilities.py
The client is again having issues with pycurl and unicode. I wasn't able to quickly determine which CMSSW/pycurl version combinations cause issues but I reproduced the problem with CMSSW_7_4_7 version and this patch should fix it. The error message in the client is this [1], I had seen the same issue before multiple times on the server as well.
[1]
`ERROR: TypeError: invalid arguments to setopt`
> Convert webdir to string to avoid problems in pycurl

- src/python/CRABClient/Commands/getcommand.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/reportold.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/status.py
Some general refactoring and additions of missing things to the API.
- I've gotten rid of the shortResult key in the status return dict because it's redundant.
- jobList in the status return dict should be taken directly from the caching results, I've previously written a loop to generate it but that was a mistake. 
- jobList will now always look like the one returned by `crab statusold --long` (It will have extra things like TotalUserCpuTimeHistory, SiteHistory, etc in addition to the state of each job). The jobList returned by `crab statusold` contains a subset of information of the `crab statusold --long` information AFAICT. It makes no sense for them to be different with the new commands since it costs us nothing to add the information regardless if the status is `--long` or not.
> Further API fixes

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/status.py
This will remove job id lists for resubmission if automatic splitting is detected - the nomenclatures clash.
> Make resubmission and status work with new automatic splitting conventions

- src/python/CRABClient/Commands/status.py
Moves the tail jobs to the very bottom of the status list using an already implemented compare function.
> Sort job ids better for long status command

- src/python/CRABClient/JobType/PrivateMC.py
As @belforte suggested in https://github.com/dmwm/CRABClient/issues/4706, this is a simple pre-submission check on how many lumis the user MC output files will have based on their configuration parameters. 
Though now re-reading the issue, do I understand it correctly? Checking the configuration params doesn't hurt but AFAIU that's not really how problematic datasets are produced. Instead, users generate events and then discard some of them before writing to output, so the "real" checking should happen before publication.
> Add client-side check for max number of output file lumis. Fix #4706

- src/python/CRABClient/Commands/resubmit.py
Companion to dmwm/CRABServer#5644 - this will give a more direct message about being unable to resubmit killed tasks with automatic splitting.
> Make kill final for automatic splitting.

- src/python/CRABClient/Commands/getcommand.py
Fix getoutput command as discovered by @lecriste in #4738.
> Make sure that "get" commands accept default splitting.

- src/python/CRABClient/Commands/status.py
Do not print warning messages when jobs use less than the default amount of RAM or when no jobs have run yet.
> Status issues

- src/python/CRABClient/Commands/status.py
Avoid getting fake warnings because based on parameters from not finished jobs (e.g. in the early stage of a task).
> Print warnings only with at least one finished job

- src/python/CRABClient/Commands/submit.py
> Avoid usage of 'maxJobRuntimeMin' with Automatic splitting

- src/python/CRABClient/Commands/status.py
Clarify the meaning of 'rescheduled' jobs in the Automatic splitting
> Improve jobs status info

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/resubmit.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/Commands/uploadlog.py
Restore original behaviour for the options of `crab uploadlog` command.
> Decouple logpath validation from validateOptions() 

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
@belforte shall I fetch this value:
https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/TaskWorker/Actions/Splitter.py#L79
instead of redefining it here:
https://github.com/dmwm/CRABClient/compare/master...lecriste:no_maxJobRuntimeMin_with_AutomaticSplitt?expand=1#diff-71ffbfee13de0d1a2aef56c45be36b39R197
?
> No max job runtime min with automatic splitt

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Reverts dmwm/CRABClient#4799 because of:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4664.html
> Revert "No max job runtime min with automatic splitt"

- src/python/CRABClient/JobType/CMSSWConfig.py
`configurationCache` does not work as intended because `os.getcwd()` is appended to `sys.path` every time a configuration file is loaded. Since `sys.path` is used as part of the key, `cacheLine`, used to fetch a cached configuration, the configuration cache is never used.
Since `sys.path` is not changed anywhere else except in the (undocumented) external plugin feature there is no reason to use it as a key to the `configurationCache`, so it can just be removed from `cacheLine` and allow the `configurationCache` to be used as intended.
(Even if `sys.path` is changed reloading the file isn't the right thing to do anyway- reloading the same CMSSW configuration file multiple times can cause crashes and difficult-to-debug incorrect behavior)
> Fixed caching of CMSSW Configuration

- src/python/CRABClient/Commands/submit.py
this will make it clear where task has been submitted to from crab submit stdout.
Mostly useful for our tests, but maybe also for users.
> when submitting, print where to

- src/python/CRABClient/Commands/status.py
Before tail jobs are created, do not remove failed jobs from main jobs and print them as rescheduled.
> Show failed (rescheduled) main jobs before tail jobs are created

- src/python/CRABClient/JobType/CMSSWConfig.py
The new crab startup script https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_1_X/master/_crab-startup.file runs in clean env but it still needs to access CMSSW's `PYTHONPATH` for `crab submit` command. I propose that crab use `CRAB_CMSSW_SITE_PACKAGES` env variable to include extra cmssw python paths when it deals with CMSSW configuration. This change should not break crab's existing setup as no one should be setting `CRAB_CMSSW_SITE_PACKAGES` env variable. 
I was abe to submit a test job with this change plus https://github.com/cms-sw/cmsdist/pull/5442/files for new crab startup script
> Add additional cmssw pythonpath if CRAB_CMSSW_SITE_PACKAGES is set

- src/python/CRABClient/JobType/CMSSWConfig.py
The current validation of PSets in CMSSWConfig.py uses ```if not getattr(...)``` in a few places to check if an attribute is defined. But ```getattr``` throws an AttributeError if the attribute is not defined, and so the helpful error message is not shown.
Adding a default of ```none``` keeps this from throwing when ```process``` and ```source``` are undefined, and does not change the behavior in other cases (e.g. when process or source are defined as ```None```).
> Fixed validation of PSets in CMSSWConfig.py

- src/python/CRABAPI/RawCommand.py
Currently, if the PSet raises a SystemExit when a job is being submitted via the CRAB API, the API raises a confusing UnboundLocalError.
The new code instead prints a traceback and then reraises the exception.
As an aside, this can still cause some confusion if the end user happens to call ```sys.exit(2)```.
Example submit script:
```
from CRABClient.UserUtilities import config
from CRABAPI.RawCommand import crabCommand
config=config()
config.Site.storageSite='T3_US_FNALLPC'
config.JobType.pluginName='PrivateMC'
config.JobType.psetName='PSet.py'
config.Data.splitting='EventBased'
config.Data.unitsPerJob=1
config.Data.totalUnits=1
config.Data.outputPrimaryDataset='None'
config.Data.publication=False
crabCommand('submit',config=config)
```
with PSet.py:
```
import sys
sys.exit(1)
``` …
> Fix PSet raising a SystemExit causing an UnboundLocalError

- src/python/CRABClient/Commands/SubCommand.py
this makes client submit if either old-style or new-style myproxy credential delegation suceeds.
Addresses #4927
> port https://github.com/dmwm/CRABClient/commit/af13445c202dd09cf135da11c1a4867ae3ef60fa to master branch

- src/python/CRABClient/Commands/checkwrite.py
Create tmp crab3checkwrite file only if lfn2pfn was successful (fix #4961)
Tested using https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabClient#Develop_for_CRABClient instructions.
> Create tmp crab3checkwrite file only if lfn2pfn was successful (fix #4961)

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/uploadlog.py
@belforte following changes will upload log file to s3 if `cacheSSL` for a given task in https://gitlab.cern.ch/crab3/CRAB3ServerConfig/-/blob/master/cmsweb-rest-config.json points to s3. otherwise logfile will be uploaded to old crabcache.
`uploadLog` to s3  only works with `crab uploadlog --dir` option. 
if `crab uploadlog --logpath` is used, log file is uploaded to old `crabcache` as in that case `cacheSSL` points to `https://cmsweb.cern.ch:8443/crabcache`. as already discussed, we should agree if `--logpath` option should be kept going forward
> upload logfile to s3 (fix #4971)

- src/python/CRABClient/CrabRestInterface.py
- src/python/CRABClient/Emulator.py
@belforte , this is first working version for discussion
however, my worry is: how to properly handle this part https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/submit.py#L134-#L136 where given on current [implementation](https://github.com/dmwm/CRABClient/compare/master...ddaina:rmvWMCoreDependency?expand=1#diff-3a235bc3a0a3f4716cc9774eaba7e5e0986d4c09f915f9b342de13229f94fcefR145) if http code != 200, it will even not reach that code part.
Be aware that PR test will not test these changes because tests uses old RESTInteractions file for deploying CRABClient.
> replace WMCore usage with curl (fix #4972)

- bin/crab
this makes crab(-dev) use python3 and work with CMSSW_12_0_0_pre6
(tested)
we can worry later about a way to pick python2/3 automatically depending on release along the lines which Shahzad suggested. As long as we keep crab-prod for CMSSW <=11 and crab-dev for CMSSW_12 only, this will suffice.
> make crab commands use python3

- src/python/CRABClient/UserUtilities.py
Once `curl` tries to get file which does not exists (http 404 error), details will still be written to `filename`. However, details are logged and file is removed.
alternative was to add `-f` flag to `curl` command and in this case file with error details would not be created at all, but as per `curl` documentation:
> In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag will prevent curl from outputting that and return error 22
this flag will prevent `curl` from outputting error, so we loose this information (while we want to keep it)
alternative to `-f` flag would be to use `--fail-with-body`, which:
> This flag will still allow curl to output and save that content but also to return …
> unlink file with error info (fix #5079)

- bin/crab.py
- src/python/CRABClient/CrabRestInterface.py
brings two changes/improvements:
1. bin/crab.py: remove check if `exitcode==503` as this is repetitive and saves us from parsing response header which is already done in CrabRestInterface.py
2. CrabRestInterface.py: reuse example from WMCore pycurl_manager how to parse HTTP response header to get HTTP code. also, now regex used in this parsing is compatible both with the header return by curl and gocurl.
tested on CMSSW_7_6_7, CMSSW_10_2_6, CMSSW_12_0_1
@belforte these are last changes that i would like to merge before creating new tag and updating IB.
> improve HTTP header parsing

- src/python/CRABClient/CrabRestInterface.py
currently it does not work because of the issue with gocurl. There is something wrong with capath variable and trying to execute command ends up with bunch of messages like this:
```
[ddirmait@lxplus768 crab_tasks]$ /cvmfs/cms.cern.ch/cmsmon/gocurl -verbose 2 -method GET -header "User-Agent: CRABClient/development" -header "Accept: */*" -data "subresource=delegatedn" -cert "/tmp/x509up_u93401" -key "/tmp/x509up_u93401" -capath "/etc/grid-security/certificates/" -url "https://cmsweb-testbed.cern.ch:8443/crabserver/preprod/info?subresource=delegatedn" | tee /dev/stderr
<...>
2021/11/30 14:39:36 main.go:231: invalid PEM format while importing trust-chain: "/etc/grid-security/certificates//036b3363.namespaces"
2021/11/30 14:39:36 main.go:231: invalid PEM format while importing trust-chain: …
```
> add gocurl option

- src/python/CRABClient/Commands/SubCommand.py
Simple PR for fixing the fact that
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
leads to a twiki that says that every relevant info was moved to
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
> Include the correct twiki link for CRAB3FAQ

- src/python/CRABClient/Commands/kill.py
This PR is required to adapt crabclient to https://github.com/dmwm/CRABServer/pull/7106
Successfully tested in preprod, where I run a REST with changes from `CRABServer/#7106`, see this https://github.com/dmwm/CRABServer/pull/7106#issuecomment-1064209192
This is requied, otherwise after deploying crabserver 7106, we save b64encoded strings in the oracle db (it is not a problem, it is just not user-friendly), see this https://github.com/dmwm/CRABServer/pull/7106#issuecomment-1064171115.
if this PR is deployed in supersync with crabserver and we end up with b64-encoded data inside the DB
```plaintext
> crab status -d crab_projects/crab_20220310_161246                                    
CRAB project directory:         /afs/cern.ch/user/d/dmapelli/crab/submit/analysis-data/crab_projects/crab_ …
```
> Do not b64-encode the custom killwarning message

- src/python/CRABClient/Commands/checkwrite.py
This was requested in https://github.com/dmwm/CRABServer/issues/7364#issuecomment-1219350157
Without this PR, `crab checkwrite` fails with
```plaintext
> crab checkwrite --checksum=yes --site=T2_IT_Pisa
Will check write permission in the default location /store/user/<username>
Validating LFN /store/user/dmapelli...
LFN /store/user/dmapelli is valid.
Will use `gfal-copy`, `gfal-rm` commands for checking write permissions
Will check write permission in /store/user/dmapelli on site T2_IT_Pisa
Will use PFN: Failed to resolve LNF to PFN via Rucio. Error is:
RSE does not support requested operation.
Details: Operation third_party_copy is not supported
srm://stormfe1.pi.infn.it:8444/srm/managerv2?SFN=/cms/store/user/dmapelli/crab3checkwrite_20220819_085201/crab3checkwrite_20220819_085201.tmp
``` …
> checkwrite - adapt to rucio 1.29 api

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Client side of https://github.com/dmwm/CRABServer/pull/7422, part of https://github.com/dmwm/CRABServer/issues/6989
> Site.requireAccelerator

- src/python/CRABClient/Commands/preparelocal.py
- src/python/CRABClient/Commands/submit.py
We need to update crab client `submit --dryrun` and `preparelocal` commands to match the new file structure introduced with https://github.com/dmwm/CRABServer/releases/tag/v3.221128 (new job wrapper)
> adapt CRABClient to new jobwrapper

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
Part of https://github.com/dmwm/CRABServer/issues/6989
Server side: https://github.com/dmwm/CRABServer/pull/7470
Add `Site.acceleratorParams` to allow user send GPU parameters as key/value.
Serializing dict to JSON string and sending it to the server. Only validate key/value on server's side.
Configuration Example:
```python
config.Site.requireAccelerator = True
config.Site.acceleratorParams = {
"CUDACapabilities": ["6.0", "6.1", "6.2", "7.0", "7.2", "7.5", "8.0", "8.6"],
"CUDARuntime": "11.4",
"GPUMemoryMB": 8000
}
```
> new Site.acceleratorParams

- src/python/CRABClient/Commands/submit.py
Related to https://github.com/dmwm/CRABServer/issues/7493 
tested
submit --dryrun needs to run for at least 25s in order not to make its estimates based on very few small events. If the first dryrun attempt is too short, the same cmsRun command is called again, with an increasing number of events. with this commit, every trial reports how long it took and how many events the next trial will process.
As suggested by stefano in https://github.com/dmwm/CRABServer/issues/7493#issuecomment-1398722319, we have
```plaintext
> crab submit --dryrun
[...]
Please wait...
Task status: UPLOADED
Created temporary directory for dry run sandbox in /tmp/dmapelli/tmpp3ytfqpx
Executing test, please wait...
Last trial took only 17.4 seconds. We are trying now with 7985 events
Last trial took only 14.0 …
```
> submit --dryrun. print info about last trial

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Analysis.py
Fix https://github.com/dmwm/CRABServer/issues/7203
Client side of https://github.com/dmwm/CRABServer/pull/7525
`Data.inputBlocks` as list of input blocks that users want to processes. 
~~Currrently drafting. We can lets users supply only blocks uuid then we concat its with inputDataset in client side.~~
~~And/or lets user supply full block name but we need to verify if dataset's name in block is same as inputDataset~~
I decide to allow users to provide either full block name or block UUID. 
- If it match UUID format, client will append dataset name for users before sending to server.
- If not, let server report error in case they forget to change dataset name.
> new Data.inputBlocks parameter

- src/python/CRABClient/JobType/Analysis.py
Fix PR https://github.com/dmwm/CRABClient/pull/5185
I misunderstand [getattr()](https://docs.python.org/3/library/functions.html#getattr) with [dict.get()](https://docs.python.org/3/library/stdtypes.html#dict.get) by assuming `getattr()` will automatically return `None` if we do not provide a default value when calling the function.
> Fix getattr with config.Data.inputBlocks

- src/python/CRABClient/JobType/UserTarball.py
Fixes #5187
tested:
This PR simply adds to the sandbox all the `python`  directories that are recursively found under `$CMSSW_BASE/src`. 
I have two questions for @belforte :
> add src/**/python to user sandbox

- src/python/CRABClient/Commands/status.py
Sub task of https://github.com/dmwm/CRABServer/issues/7797
(See the line after `Job status:`) Changing from 
```
Rucio Container:  user.tseethon:/GenericTTbar/tseethon-ruciotransfers-1-94ba0e06145abd65ccb1d21786dc7e1d/USER
Tips on how to check on Rucio StageOut at https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#Stageout_with_Rucio 
```
To 
```
Transfer container's rule: https://cms-rucio-webui.cern.ch/rule?rule_id=5dd94c3731994a8f8251571a7f5aab9c
Tips on how to check on Rucio StageOut at https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#Stageout_with_Rucio 
```
> Print rule id instead of container name in "crab status" command

- bin/rucio_env.sh
if one has CMSSW setup for a different arch than the current machine (e.g. do cmsrel on SL7 and than run on SL8, which works) the `/cvmfs/cms.cern.ch/rucio/setup-py3.sh` will get confused and fail to resolve dependencies.
This PR makes sure that Rucio is setup in the pre-cmsenv environment.
> avoid rucio setup getting confused by existing CMSSW stuff

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/Commands/SubCommand.py
reference: https://cms-talk.web.cern.ch/t/unannounced-change-in-crab-parameters/31937/2
> add deprecation reason for sendPythonFolder

- src/python/CRABClient/ClientExceptions.py
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/checkwrite.py
- src/python/CRABClient/Commands/status.py
Together with CRABServer PR https://github.com/dmwm/CRABServer/pull/7987
Use isEnoughRucioQuota from CRABServer's `ServerUtilities.py`, minimum CRABServer version is [v3.231103](https://github.com/dmwm/CRABServer/releases/tag/v3.231103).
~~Note for one big change; I have moved initialize Rucio client to SubCommand class method because we need to get proper Rucio account to get account usage. You can only allow to get usage from your own account unless you have admin privilege. The problem occur when we want to use group area where it has different account.~~
~~In example, users want store outputs to Rucio group area which need different Rucio account (In our case, we need `crab_test_group` account, not `belforte` or `dmapelli` account). To get the account, we parse the LFN by using …
> Use isEnoughRucioQuota from ServerUtilities.py

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/checkdataset.py
- src/python/CRABClient/Commands/checkfile.py
- src/python/CRABClient/Commands/remake.py
- src/python/CRABClient/Commands/tasks.py
- src/python/CRABClient/UserUtilities.py
also introduce `commandUsedInsideCrab()` function in `ClientUtilities` so that we can decide if/when to use `print()` in a command for extra-verbosity of "progress report in same line" which only applies when using `crab` command, not the python Client API
> Move checkdataset to crab client repo fix 5233

- src/python/CRABClient/CRABOptParser.py
- src/python/CRABClient/Commands/SubCommand.py
Fixes #5268 
Tested and approved in https://github.com/dmwm/CRABClient/pull/5250#issuecomment-1836046811
first execution
```plaintext
Singularity> crab status --task=231031_085905:sesanche_crab_QCD_Pt800to1000_Mu5 --proxy=$X509_USER_PROXY
crab status requires a projdir. Since you passed a taskname, we will run crab remake
Remaking crab_QCD_Pt800to1000_Mu5 folder.
Remaking .requestcache file.
Success: Finished remaking project directory crab_QCD_Pt800to1000_Mu5
Rucio client intialized for account dmapelli
CRAB project directory:         /home/dario/crab/local/z-submitted/crab_QCD_Pt800to1000_Mu5
Task name:                      231031_085905:sesanche_crab_QCD_Pt800to1000_Mu5
[...]
```
Second time: crab remake returns a warning, crab status runs properly. Of course, you can run crab status …
> all crab commands that require a projdir can be called with --task=

- src/python/CRABClient/ClientMapping.py
- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/Commands/getsandbox.py
- src/python/CRABClient/Commands/recover.py
- src/python/CRABClient/Commands/remake.py
- src/python/CRABClient/Commands/report.py
- src/python/CRABClient/Commands/submit.py
- src/python/CRABClient/JobType/Recover.py
- src/python/CRABClient/UserUtilities.py
First implementation of automatic submission of a recovery task, without the need for users to follow instructions at [1]
how to trigger this new functionality: from crab client, run `crab recover --task=<taskname>`.
This command **supports** the recovery task for a task that
- has jobtype analysis
- uses a splitting algorithm that is aware of lumisections (automatic, lumibased, eventawarelumibased)
This command supports, but we have **not thoroughly** tested
- recover of a task submitted with automatic splitting [**]. User are encouraged to use it, but some extra caution may be needed.
does **not** support recovery of a task
- filebased splitting: will be done at a later stage
- privatemc: makes little sense, a user can just submit a new task.
changes  since out chat on 2023-11-10 …
> crab recover - new command

- src/python/CRABClient/JobType/Analysis.py
reference https://cms-talk.web.cern.ch/t/impossible-to-run-crab-jobs/33451/17
> properly report invalid run_range in config

- src/python/CRABClient/Commands/checkwrite.py
Fix https://github.com/dmwm/CRABClient/issues/5296
Need to add suffix uuid to both `self.filename` and `self.subdir` because we also test deleting directory.
Tested manually on el7 CMSSW_10_6_40 and el8 CMSSW_13_0_2.
(Did not test on slc6 because there is no `checkwrite` in command list of CV)
> Add suffix uuid string to filename and subdir

- etc/crab-bash-completion.sh
- scripts/generate_completion.py
fixes #5314 
tested on my laptop, but i have a small question before merging
This PR serves multiple purposes:
- make bash autocompletion respect the order at which we provide the commands. see the use of `-o nosort` in `complete -F _UseCrab -o filenames -o nosort crab`
- do not edit the `etc/crab-bashpcimpletion.sh` directly, generate it programmatically from `scripts/generate-completions.py`
- make `generate-completions.py` work with python3
- use `importlib` instead of  `imp`
- make `generate-completions.py` generate the completion in our desired ordering, see the use of the `weights` variable.
open questions:
- take a look at `etc/crab-bash-completion.sh` line 26. the order here is what bash shows when you press `crab <tab><tab>` (the order of line 32 will be the same as line 26)
- …
> completions - generate_completions script works in py3

- src/python/CRABClient/ClientUtilities.py
- src/python/CRABClient/Commands/checkfile.py
- src/python/CRABClient/CredentialInteractions.py
- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/JobType/ScramEnvironment.py
- src/python/CRABClient/JobType/UserTarball.py
- test/python/CRABClient_t/JobType_t/CMSSW_t.py
Hello. I found some typos in python files (non-frozen). Also changed the on-page paragraph link for the cmsenv setup section that had lost its target.
> Fix typos in output messages and subsection TWiki link for cmsenv

- src/python/CRABClient/Commands/report.py
fix #5325
tested, the `failedLumis.json` file is produced [1]
---
[1]:
<details>
```plaintext
Singularity> crab report -d crab_EGammaEXO_Run2018A_20240704_231147 --proxy=$X509_USER_PROXY --recovery=failed
Running crab status first to fetch necessary information.
Rucio client intialized for account dmapelli
Will save lumi files into output directory /home/dario/crab/local/z-submitted/crab_EGammaEXO_Run2018A_20240704_231147/results
Summary from jobs in status 'finished':
Number of files processed: 2860
Number of events read: 3848368
Number of events written in EDM files: 0
Number of events written in TFileService files: 0
Number of events written in other type of files: 0
Processed lumis written to processedLumis.json
Warning: 'failed' lumis written to failedLumis.json
The 'failed' lumis …
```
> report - fix bug in --recovery=failed

- src/python/CRABClient/Commands/SubCommand.py
- src/python/CRABClient/JobType/CMSSWConfig.py
- src/python/CRABClient/WMCoreConfiguration.py
- src/python/CRABClient/__init__.py
- test/python/CRABClient_t/Commands_t/CRABRESTModelMock.py
- test/python/CRABClient_t/Commands_t/Commands_t.py
`imp` module has been deprecated and removed in `python 3.12`. This PR proposes to uses `importlib` for `python 3.12` e.g in `CMSSW_14_2_PY3_12_X` IBs. It should not break crab client for CMSSW release with `python version < 3.12`.
This requires newer WMCore specially change in [WMCore/Configuration.py](https://github.com/dmwm/WMCore/pull/11530/files#diff-ae418221154baa0ba96bdcf0566fde2fccf43a95d289f435f28c45e2a0552f1b) . 
Note that using this I was able to submit crab job for CMSSW_14_2_PY312_X but they [fail on crab server side](https://cmsweb.cern.ch:8443/scheddmon/0195/cmsbot/241121_102531:cmsbot_crab_Jenkins_CMSSW_14_2_PY312_X_2024-11-20-2300_el8_amd64_gcc12_123400/job_out.1.0.txt) as due to usage of `imp` in crab server code. So in order to fully support python 3.12 crab jobs, one …
> Python3.12 support: Use importlib instead of deprecated imp module

- test/python/CRABClient_t/Commands_t/Commands_t.py
This fixes a typo introduced in https://github.com/dmwm/CRABClient/pull/5350
> Typo fixed: import load_source from CRABClient

- src/python/CRABClient/Commands/submit.py
after this:
```console
belforte@lxplus813/TC3> crab submit --dryrun 
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration dummyanalyzer.py
Finished importing CMSSW configuration dummyanalyzer.py
Sending the request to the server at cmsweb.cern.ch
Success: Your task has been delivered to the prod CRAB3 server.
Task name: 250409_151806:belforte_crab_20250409_171801
Project dir: ./crab_20250409_171801
Waiting for task to be processed
Checking task status
Task status: WAITING
Please wait...
Task status: NEW
Please wait...
Task status: UPLOADED
Dry run
Getting input files into tmp dir /tmp/belforte/tmpk4p3vqb_
Copying and preparing files for local execution in /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20250409_171801/local
go to that directory IN A CLEAN SHELL and use …
```
> make submit dryrun work with TW v3.250401 Fix #5383

- src/python/CRABClient/Commands/preparelocal.py
thanks for the hint @aspiringmind-code .
I have minimally changed to avoid `sh run_job 0` which also fails.
Please check whether you still like it.
> ensure that a valid jobId is passed to run_job.sh. Fix #5390
